/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class TestUI extends View {
		public list:Laya.List;
		public checkOpenBatch:Laya.CheckBox;
        public static  uiView:any ={"type":"View","props":{"width":640,"runtime":"Test.ts","height":1136},"compId":2,"child":[{"type":"Image","props":{"y":102,"x":69,"width":524,"skin":"comp/img_bg.png","sizeGrid":"60,22,16,15","height":663},"compId":5},{"type":"List","props":{"y":157,"x":74,"width":516,"var":"list","repeatX":1,"height":593},"compId":4},{"type":"CheckBox","props":{"y":23,"x":292,"var":"checkOpenBatch","skin":"comp/checkbox.png","labelSize":26,"labelPadding":"20","labelColors":"#FF0000,#FFFF00,#00FF00","label":"是否开启合批"},"compId":8}],"loadList":["comp/img_bg.png","comp/checkbox.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(TestUI.uiView);
        }
    }
    REG("ui.TestUI",TestUI);
    export class TestRenderUI extends View {
		public btn:Laya.Button;
		public txtName:Laya.Text;
		public clip:Laya.Clip;
        public static  uiView:any ={"type":"View","props":{"width":516,"height":50},"compId":2,"child":[{"type":"Button","props":{"y":1,"x":194,"var":"btn","skin":"comp/button.png","labelStrokeColor":"#000000","labelStroke":2,"labelSize":20,"labelColors":"#00FF00","label":"按钮"},"compId":3},{"type":"Text","props":{"y":14,"x":0,"width":171,"var":"txtName","text":"测试文本","fontSize":22,"color":"#d600ff","runtime":"Laya.Text"},"compId":4},{"type":"Clip","props":{"y":-7,"x":490,"var":"clip","skin":"comp/clip_num.png","clipX":10},"compId":5}],"loadList":["comp/button.png","comp/clip_num.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(TestRenderUI.uiView);
        }
    }
    REG("ui.TestRenderUI",TestRenderUI);
}